---
# Full documentation: https://ansible-lint.readthedocs.io/en/latest/index.html
exclude_paths:
    - ../../.cache/
    - .cache/
    - .github/
    - .hooks/
    - .vscode/
    - archived_data/
    - galaxy-roles/
    - .cz.yaml
    - vault.yml
    - .venv/
    - ansible_collections/
skip_list:
    - yaml[indentation]
#     - name[template]
#     - ignore-errors
#     - meta-incorrect
#     - meta-no-info
#     - package-latest
#     - role-name
#     - unnamed-task
#     - var-naming
#     - latest[git]

# warn_list:
#     - experimental
#     - risky-file-permissions
#     - command-instead-of-module
#     - no-changed-when
#     - command-instead-of-shell
